### ISSUE TITLE
The app crashed when tried to use a song as my phone's ringtone

### ISSUE THREAD

**Issue by sagorahmed** [hvdwolf/aosp-music#1]
#### Expected behavior
The users should be able to use a song as the phone ringtone without the app crash.

#### Actual behavior
When I tried to use a song as my phone ringtone, then the app crashed.

#### How to reproduce
1. Open the app.
2. Choose a song.
3. Tap on it and hold for a while.
4. Then click "Use as phone ringtone" and a few seconds later notice the error.

* App version: 1.3
* Operating system: Android 6.0.1

#### Recording Of The Bug
![bug](https://media.giphy.com/media/VFqdARElGkOJ4bArA6/giphy.gif)

#### LogCat
```
04-30 09:18:23.162 28048 28048 E AndroidRuntime: FATAL EXCEPTION: main

04-30 09:18:23.162 28048 28048 E AndroidRuntime: Process: com.android.music, PID: 28048

04-30 09:18:23.162 28048 28048 E AndroidRuntime: java.lang.SecurityException: com.android.music was not granted  this permission: android.permission.WRITE_SETTINGS.

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1620)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:646)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at android.provider.Settings$NameValueCache.putStringForUser(Settings.java:1457)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at android.provider.Settings$System.putStringForUser(Settings.java:1867)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at android.provider.Settings$System.putString(Settings.java:1845)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at com.android.music.MusicUtils.setRingtone(MusicUtils.java:1120)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at com.android.music.TrackBrowserActivity.onContextItemSelected(TrackBrowserActivity.java:682)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at android.app.Activity.onMenuItemSelected(Activity.java:3246)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DialogMenuCallback.onMenuItemSelected(PhoneWindow.java:5787)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:801)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:954)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:944)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:172)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1228)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:346)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1550)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3830)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:5855)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

04-30 09:18:23.162 28048 28048 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by hvdwolf** [comment]
Hi.

I can reproduce your issue. I'm not sure whether I can solve it, but I will investigate it.
Please note that as work-around you can do the same from Settings -> sound -> ringtone

**Comment by sagorahmed** [comment]
Hello @hvdwolf 
Thanks for your fast reply. Hopefully, you will sort out this issue soon.
